### ISSUE TITLE
Python=3.7 can't install numpy=2.2.0

### ISSUE THREAD

**Issue by NineSeven0** [wwh0411/FedRSU#1]
I ran python setup.py install in pypcd and it showed numpy=2.2.0 is required. But python=3.7 can't install numpy=2.2.0. Is python=3.7 necessary?

**Comment by wwh0411** [comment]
No, python=3.7 is not a strict requirement. We included it in the README.md because our experimental environment was based on python 3.7, and it's provided for reference. You may upgrade to other python versions if they work fine.

**Comment by NineSeven0** [comment]
Okay i got it.Thanks.
